// Do not edit. This file is machine generated by the Resource DLL Wizard.

library VETune;

{ITE} {DFMFileType} {Unit1.dfm}
{ITE} {DFMFileType} {Unit2.dfm}
{ITE} {DFMFileType} {Unit3.dfm}
{ITE} {DFMFileType} {Unit4.dfm}
{ITE} {RCFileType} {Release\Win32\VETune_DRC.rc}

{$R 'Unit1.dfm' Form1:TForm}
{$R 'Unit2.dfm' Form2:TForm}
{$R 'Unit3.dfm' Form3:TForm}
{$R 'Unit4.dfm' Form4:TForm}
{$R 'Release\Win32\VETune_DRC.res' 'Release\Win32\VETune_DRC.rc'}

{$E ENU}

begin
end.
